/**
 * Dora Long-Term Memory Store
 * Phase 2 — Step 3: Memory Consolidation & Lifecycle (Storage Boundary)
 * 
 * Provides a clean, isolated persistence boundary for persistent user memories.
 * Decouples cognitive engines (Reasoning, Planning, Verification, Retrieval, Consolidation)
 * from data storage, supporting in-memory storage now and easy future migration to Redis/DB.
 */

import {
  MemoryRecord,
  MemoryDecision,
  MemoryForgetDirective,
  MemoryType,
  MemorySource,
  MemoryStatus,
} from "./memoryTypes";
import { memoryConsolidationEngine } from "./memoryConsolidationEngine";
import { MemoryConsolidationResult } from "./memoryConsolidationTypes";
import { LearningPattern } from "./adaptiveLearningTypes";

export class MemoryStore {
  private static instance: MemoryStore;
  
  // Storage indexed by userId (e.g. "default", session ID, or user ID)
  private memoryMap: Map<string, MemoryRecord[]> = new Map();
  // Adaptive learned patterns storage indexed by userId
  private patternMap: Map<string, LearningPattern[]> = new Map();

  private constructor() {}

  public static getInstance(): MemoryStore {
    if (!MemoryStore.instance) {
      MemoryStore.instance = new MemoryStore();
    }
    return MemoryStore.instance;
  }

  public deterministicHash(str: string): string {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = (hash << 5) - hash + str.charCodeAt(i);
      hash |= 0;
    }
    return Math.abs(hash).toString(16);
  }

  /**
   * Retrieves a cloned snapshot of all memory records for a given user.
   * Never returns raw internal mutable references.
   */
  public get(userId: string = "default"): MemoryRecord[] {
    const records = this.memoryMap.get(userId) || [];
    return records.map((r) => ({ ...r, tags: [...(r.tags || [])], evidence: [...(r.evidence || [])] }));
  }

  /**
   * Retrieves only retrievable active memories for a given user (excluding DELETED, SUPERSEDED, EXPIRED, OUTDATED, ARCHIVED, quarantined).
   */
  public getActive(userId: string = "default"): MemoryRecord[] {
    const all = this.get(userId);
    return all.filter(
      (m) =>
        m.status === "ACTIVE" &&
        !m.isQuarantined &&
        m.value !== "[REDACTED_SENSITIVE_DATA]" &&
        (!m.expiresAt || Date.now() < m.expiresAt)
    );
  }

  /**
   * Retrieves a single memory record by ID for a user.
   */
  public getById(userId: string = "default", id: string): MemoryRecord | undefined {
    const all = this.get(userId);
    return all.find((m) => m.id === id);
  }

  /**
   * Replaces the entire memory pool for a user with the provided records.
   */
  public replace(userId: string = "default", memories: MemoryRecord[]): void {
    const cloned = memories.map((r) => ({
      ...r,
      userId: r.userId || userId,
      tags: [...(r.tags || [])],
      evidence: [...(r.evidence || [])],
    }));
    this.memoryMap.set(userId, cloned);
  }

  /**
   * Saves or inserts a single memory record for a user.
   */
  public save(userId: string = "default", record: MemoryRecord): MemoryRecord {
    const existing = this.get(userId);
    const index = existing.findIndex((m) => m.id === record.id);
    const toSave: MemoryRecord = {
      ...record,
      userId: record.userId || userId,
      tags: [...(record.tags || [])],
      evidence: [...(record.evidence || [])],
    };

    if (index !== -1) {
      existing[index] = toSave;
    } else {
      existing.push(toSave);
    }

    this.replace(userId, existing);
    return toSave;
  }

  /**
   * Applies and persists a MemoryDecision generated by MemoryDecisionEngine.
   */
  public applyDecision(
    userId: string = "default",
    decision: MemoryDecision,
    currentTime: number = Date.now()
  ): MemoryRecord | undefined {
    if (!decision || decision.action === "IGNORE") {
      return undefined;
    }

    const pool = this.get(userId);

    // 1. FORGET directive
    if (decision.action === "FORGET") {
      const directive: MemoryForgetDirective = decision.forgetDirective || {
        keyOrTopic: decision.targetRecord?.key || "all",
        scope: "exact",
        reason: decision.reason,
      };
      const forgetResult = memoryConsolidationEngine.executeForget(pool, directive, currentTime);
      this.replace(userId, forgetResult.updatedMemories);
      return undefined;
    }

    const target = decision.targetRecord;
    if (!target || !target.key || !target.value) {
      return undefined;
    }

    const normKey = target.key.toLowerCase().trim().replace(/[\s-]+/g, "_");
    const normVal = target.value.toLowerCase().trim();

    // 2. Sensitive data quarantine check
    const isSensitive =
      decision.isSensitiveRejected ||
      /\b(?:password|passwd|api_key|sk-[a-zA-Z0-9]{20,}|bearer\s+[a-zA-Z0-9_\-\.]{20,}|cvv|pin\s*\d{4,6})\b/i.test(
        `${target.key} ${target.value}`
      );

    if (isSensitive) {
      const quarantinedRecord: MemoryRecord = {
        id: target.id || `mem_${this.deterministicHash(`${userId}_sensitive_${normKey}_${currentTime}`)}`,
        userId,
        type: (target.type as MemoryType) || "FACT",
        key: normKey,
        value: "[REDACTED_SENSITIVE_DATA]",
        normalizedValue: "[redacted_sensitive_data]",
        source: target.source || (decision.isExplicit ? "EXPLICIT_USER" : "INFERRED"),
        confidence: 1.0,
        importance: 0,
        createdAt: target.createdAt || currentTime,
        updatedAt: currentTime,
        lastAccessedAt: currentTime,
        accessCount: 1,
        status: "DELETED",
        tags: ["quarantined", "sensitive"],
        evidence: [],
        isQuarantined: true,
        quarantineReason: "Sensitive credential or token rejected by policy",
        version: 1,
      };
      pool.push(quarantinedRecord);
      this.replace(userId, pool);
      return quarantinedRecord;
    }

    // 3. UPDATE action (Supersedes existing active record for the same key)
    if (decision.action === "UPDATE") {
      const existingIdx = pool.findIndex(
        (m) =>
          m.id === decision.existingRecordId ||
          (m.status === "ACTIVE" && m.key.toLowerCase().trim().replace(/[\s-]+/g, "_") === normKey)
      );

      let predecessorId: string | null = null;
      let prevVersion = 0;

      if (existingIdx !== -1) {
        const old = pool[existingIdx];
        predecessorId = old.id;
        prevVersion = old.version || 1;
      }

      const newId = target.id || `mem_${this.deterministicHash(`${userId}_${normKey}_${normVal}_${prevVersion + 1}`)}`;

      if (existingIdx !== -1) {
        const old = pool[existingIdx];
        // Mark old as SUPERSEDED
        pool[existingIdx] = {
          ...old,
          status: "SUPERSEDED",
          supersededBy: newId,
          updatedAt: currentTime,
          version: prevVersion + 1,
        };
      }

      const updatedRecord: MemoryRecord = {
        id: newId,
        userId,
        type: (target.type as MemoryType) || "PREFERENCE",
        key: target.key,
        value: target.value,
        normalizedValue: normVal,
        source: (target.source as MemorySource) || (decision.isExplicit ? "EXPLICIT_USER" : "INFERRED"),
        confidence: decision.isExplicit ? 1.0 : (target.confidence ?? decision.confidence ?? 0.85),
        importance: target.importance ?? 80,
        createdAt: target.createdAt || currentTime,
        updatedAt: currentTime,
        lastAccessedAt: currentTime,
        accessCount: 1,
        status: "ACTIVE",
        tags: target.tags || [],
        evidence: target.evidence || (decision.reason ? [decision.reason] : []),
        supersedes: predecessorId,
        version: prevVersion + 1,
      };

      pool.push(updatedRecord);
      this.replace(userId, pool);
      return updatedRecord;
    }

    // 4. CANDIDATE action (Creates unpromoted candidate memory)
    if (decision.action === "CANDIDATE") {
      const candidateRecord: MemoryRecord = {
        id: target.id || `mem_cand_${this.deterministicHash(`${userId}_${normKey}_${normVal}`)}`,
        userId,
        type: "CANDIDATE",
        key: target.key,
        value: target.value,
        normalizedValue: normVal,
        source: (target.source as MemorySource) || "INFERRED",
        confidence: target.confidence ?? decision.confidence ?? 0.65,
        importance: target.importance ?? 50,
        createdAt: target.createdAt || currentTime,
        updatedAt: currentTime,
        lastAccessedAt: currentTime,
        accessCount: 1,
        reinforcementCount: 1,
        status: "CANDIDATE",
        tags: target.tags || [],
        evidence: target.evidence || (decision.reason ? [decision.reason] : []),
        version: 1,
      };

      pool.push(candidateRecord);
      this.replace(userId, pool);
      return candidateRecord;
    }

    // 5. TEMPORARY action (Creates time-bounded memory)
    if (decision.action === "TEMPORARY") {
      const expiresAt = target.expiresAt || currentTime + 3 * 24 * 60 * 60 * 1000;
      const tempRecord: MemoryRecord = {
        id: target.id || `mem_temp_${this.deterministicHash(`${userId}_${normKey}_${normVal}`)}`,
        userId,
        type: "TEMPORARY",
        key: target.key,
        value: target.value,
        normalizedValue: normVal,
        source: (target.source as MemorySource) || (decision.isExplicit ? "EXPLICIT_USER" : "INFERRED"),
        confidence: decision.isExplicit ? 1.0 : (target.confidence ?? 0.8),
        importance: target.importance ?? 40,
        createdAt: target.createdAt || currentTime,
        updatedAt: currentTime,
        lastAccessedAt: currentTime,
        accessCount: 1,
        expiresAt,
        status: "ACTIVE",
        tags: target.tags || ["temporary"],
        evidence: target.evidence || [],
        version: 1,
      };

      pool.push(tempRecord);
      this.replace(userId, pool);
      return tempRecord;
    }

    // 6. SAVE action (Standard persistent memory)
    if (decision.action === "SAVE") {
      // Check if existing identical active memory exists -> update/reinforce rather than duplicate
      const existingIdx = pool.findIndex(
        (m) =>
          m.status === "ACTIVE" &&
          m.key.toLowerCase().trim().replace(/[\s-]+/g, "_") === normKey &&
          m.value.toLowerCase().trim() === normVal
      );

      if (existingIdx !== -1) {
        const existing = pool[existingIdx];
        const reinforced = memoryConsolidationEngine.reinforceMemory(
          existing,
          decision.reason || "Reinforced via explicit statement",
          currentTime,
          decision.isExplicit
        );
        pool[existingIdx] = reinforced.updatedMemory;
        this.replace(userId, pool);
        return reinforced.updatedMemory;
      }

      // Check if conflicting active memory exists -> supersede old
      const conflictingIdx = pool.findIndex(
        (m) =>
          m.status === "ACTIVE" &&
          m.key.toLowerCase().trim().replace(/[\s-]+/g, "_") === normKey &&
          m.value.toLowerCase().trim() !== normVal
      );

      let supersededId: string | null = null;
      let prevVersion = 0;

      if (conflictingIdx !== -1) {
        const old = pool[conflictingIdx];
        supersededId = old.id;
        prevVersion = old.version || 1;
      }

      const newId = target.id || `mem_${this.deterministicHash(`${userId}_${normKey}_${normVal}`)}`;

      if (conflictingIdx !== -1) {
        const old = pool[conflictingIdx];
        pool[conflictingIdx] = {
          ...old,
          status: "SUPERSEDED",
          supersededBy: newId,
          updatedAt: currentTime,
          version: prevVersion + 1,
        };
      }

      const savedRecord: MemoryRecord = {
        id: newId,
        userId,
        type: (target.type as MemoryType) || "PREFERENCE",
        key: target.key,
        value: target.value,
        normalizedValue: normVal,
        source: (target.source as MemorySource) || (decision.isExplicit ? "EXPLICIT_USER" : "INFERRED"),
        confidence: decision.isExplicit ? 1.0 : (target.confidence ?? decision.confidence ?? 0.9),
        importance: target.importance ?? 80,
        createdAt: target.createdAt || currentTime,
        updatedAt: currentTime,
        lastAccessedAt: currentTime,
        accessCount: 1,
        reinforcementCount: 1,
        status: "ACTIVE",
        tags: target.tags || [],
        evidence: target.evidence || (decision.reason ? [decision.reason] : []),
        supersedes: supersededId,
        version: prevVersion + 1,
      };

      pool.push(savedRecord);
      this.replace(userId, pool);
      return savedRecord;
    }

    return undefined;
  }

  /**
   * Applies the results of a maintenance sweep back to storage.
   */
  public applyMaintenance(
    userId: string = "default",
    memoriesOrResult: MemoryRecord[] | MemoryConsolidationResult
  ): void {
    const records = Array.isArray(memoriesOrResult)
      ? memoriesOrResult
      : memoriesOrResult.updatedMemories;
    this.replace(userId, records);
  }

  /**
   * Explicitly forgets memories for a user based on exact key, topic, or all.
   */
  public forget(
    userId: string = "default",
    targetKeyOrTopic: string,
    scope: "exact" | "topic" | "all" = "exact",
    currentTime: number = Date.now()
  ): { forgottenCount: number; updatedMemories: MemoryRecord[] } {
    const pool = this.get(userId);
    const directive: MemoryForgetDirective = {
      keyOrTopic: targetKeyOrTopic,
      scope,
      reason: `Explicit user forget directive for '${targetKeyOrTopic}'`,
    };
    const result = memoryConsolidationEngine.executeForget(pool, directive, currentTime);
    this.replace(userId, result.updatedMemories);
    return {
      forgottenCount: result.forgottenCount,
      updatedMemories: result.updatedMemories,
    };
  }

  /**
   * Retrieves cloned adaptive learning patterns for a user.
   */
  public getPatterns(userId: string = "default"): LearningPattern[] {
    const patterns = this.patternMap.get(userId) || [];
    return patterns.map((p) => ({
      ...p,
      evidence: p.evidence.map((e) => ({ ...e })),
      directives: p.directives ? [...p.directives] : undefined,
    }));
  }

  /**
   * Replaces all learned patterns for a user.
   */
  public replacePatterns(userId: string = "default", patterns: LearningPattern[]): void {
    const cloned = patterns.map((p) => ({
      ...p,
      userId: p.userId || userId,
      evidence: p.evidence.map((e) => ({ ...e })),
      directives: p.directives ? [...p.directives] : undefined,
    }));
    this.patternMap.set(userId, cloned);
  }

  /**
   * Saves or updates a single learning pattern for a user.
   */
  public savePattern(userId: string = "default", pattern: LearningPattern): LearningPattern {
    const existing = this.getPatterns(userId);
    const index = existing.findIndex((p) => p.id === pattern.id);
    const toSave: LearningPattern = {
      ...pattern,
      userId: pattern.userId || userId,
      evidence: pattern.evidence.map((e) => ({ ...e })),
      directives: pattern.directives ? [...pattern.directives] : undefined,
    };

    if (index !== -1) {
      existing[index] = toSave;
    } else {
      existing.push(toSave);
    }

    this.replacePatterns(userId, existing);
    return toSave;
  }

  /**
   * Clears all patterns for a specific user.
   */
  public clearPatterns(userId: string = "default"): void {
    this.patternMap.delete(userId);
  }

  /**
   * Clears all memories and patterns for a specific user.
   */
  public clear(userId: string = "default"): void {
    this.memoryMap.delete(userId);
    this.patternMap.delete(userId);
  }

  /**
   * Clears memory and pattern storage across all users (useful for testing).
   */
  public clearAll(): void {
    this.memoryMap.clear();
    this.patternMap.clear();
  }
}

export const memoryStore = MemoryStore.getInstance();
